### ISSUE TITLE
Add github actions to build & deploy the website, remove ./build folder

### ISSUE THREAD

**Issue by yzevm** [Grimace-Labs/GrimaceSwap#6]

**Comment by Normalizex** [comment]
Building in the main/master branch In our case, this is not the best tone.

Github supports 2 deployment methods, "Github Actions" and "Deploy from branch".
At the moment,  we have "deploy from a branch", but as I understand it, the branch for deployment is "master"?

I suggest:

1. Remove ./build folder from the master branch. 
2. Add ./build folder to .gitignore
3. Update deploy files in "gh-pages"
4. Change branch for deployment from "master" to "gh-pages".

![image](https://github.com/Grimace-Labs/GrimaceSwap/assets/104392358/c08cee31-5e8e-4d64-ac75-35d2a12234f0)

This is a temporary solution for the moment, I will try to deploy the next versions through github actions.

**Comment by yzevm** [comment]
@Normalizex https://github.com/Grimace-Labs/GrimaceSwap/pull/12
